export default class Constants2 {
    static EXTENSION_ID = "ncmkihhmjnhdkmfemcabkcepadafdehg";
    static MAIN_STORAGE_PORT = "MAIN:STORAGE";
    static EXTENSION_MAIN_PORT = "EXTENSION-MAIN";
    static STUN_SERVERS = ["stun:stun1.l.google.com:19302", "stun:stun2.l.google.com:19302"];
    static ICE_CANDIDATE_POOL_SIZE = 10;
    static LOCAL_STREAM_MANIPULATED_EVENT = "LOCAL:STREAM_MANIPULATED";
    static REMOTE_STREAM_MANIPULATED_EVENT = "REMOTE:STREAM_MANIPULATED";
    static EXTENSION_DETAILS = "EXTENSION:EXTENSION_DETAILS_TRANSMISSION";
    static CREATE_SESSION = "EXTENSION:CREATE_SESSION";
    static PLAY = "PLAY";
    static PAUSE = "PAUSE";
    static EXTENSION_MAIN_CONNECTION_ESTABLISHED = "EXTENSION-MAIN:ESTABLISHED";
    static STORAGE_SET = "STORAGE:SET";
    static STORAGE_GET = "STORAGE:GET";
}